# Generated by Django 4.2.10 on 2024-03-08 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 3, 8, 11, 26, 7, 706448, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
